@echo off
setlocal
set "INCIDENTSEAL_PYTHONPATH=%~dp0src"
if defined PYTHONPATH set "INCIDENTSEAL_PYTHONPATH=%INCIDENTSEAL_PYTHONPATH%;%PYTHONPATH%"
set "PYTHONPATH=%INCIDENTSEAL_PYTHONPATH%"
python -m incidentseal %*
