@echo off
setlocal
set "INCIDENTSEAL_DASHBOARD_PYTHONPATH=%~dp0src"
if defined PYTHONPATH set "INCIDENTSEAL_DASHBOARD_PYTHONPATH=%INCIDENTSEAL_DASHBOARD_PYTHONPATH%;%PYTHONPATH%"
set "PYTHONPATH=%INCIDENTSEAL_DASHBOARD_PYTHONPATH%"
python -B -m incidentseal.dashboard_surface %*
